import { ParkingSlotResource, VehiclePCB, AuditLogEntry, SchedulerConfig } from './types';
import { DEFAULT_CONFIG } from './scheduler';

export const INITIAL_SLOTS: ParkingSlotResource[] = [
  // Zone A - Premium Proximity (10m - 35m)
  {
    id: 'SLOT-A01',
    zone: 'Zone A',
    type: 'STANDARD',
    distance: 12,
    state: 'OCCUPIED',
    currentVehicleId: 'PROC-101',
    reservedForVehicleId: null,
    occupiedSince: 0,
    expectedReleaseTime: 25, // Leaves at t=25
    reservationExpiresAt: null,
    totalVehiclesServed: 3,
  },
  {
    id: 'SLOT-A02',
    zone: 'Zone A',
    type: 'EV_CHARGER',
    distance: 18,
    state: 'OCCUPIED',
    currentVehicleId: 'EV-IONIQ-5',
    reservedForVehicleId: null,
    occupiedSince: 5,
    expectedReleaseTime: 40,
    reservationExpiresAt: null,
    totalVehiclesServed: 2,
  },
  {
    id: 'SLOT-A03',
    zone: 'Zone A',
    type: 'ACCESSIBLE',
    distance: 15,
    state: 'FREE',
    currentVehicleId: null,
    reservedForVehicleId: null,
    occupiedSince: null,
    expectedReleaseTime: null,
    reservationExpiresAt: null,
    totalVehiclesServed: 4,
  },
  {
    id: 'SLOT-A04',
    zone: 'Zone A',
    type: 'VIP',
    distance: 22,
    state: 'FREE',
    currentVehicleId: null,
    reservedForVehicleId: null,
    occupiedSince: null,
    expectedReleaseTime: null,
    reservationExpiresAt: null,
    totalVehiclesServed: 1,
  },
  {
    id: 'SLOT-A05',
    zone: 'Zone A',
    type: 'STANDARD',
    distance: 28,
    state: 'FREE',
    currentVehicleId: null,
    reservedForVehicleId: null,
    occupiedSince: null,
    expectedReleaseTime: null,
    reservationExpiresAt: null,
    totalVehiclesServed: 2,
  },
  {
    id: 'SLOT-A06',
    zone: 'Zone A',
    type: 'EV_CHARGER',
    distance: 35,
    state: 'FREE',
    currentVehicleId: null,
    reservedForVehicleId: null,
    occupiedSince: null,
    expectedReleaseTime: null,
    reservationExpiresAt: null,
    totalVehiclesServed: 3,
  },

  // Zone B - Core Deck (45m - 75m)
  {
    id: 'SLOT-B01',
    zone: 'Zone B',
    type: 'STANDARD',
    distance: 48,
    state: 'OCCUPIED',
    currentVehicleId: 'PROC-102',
    reservedForVehicleId: null,
    occupiedSince: 2,
    expectedReleaseTime: 18, // Imminent exit at t=18!
    reservationExpiresAt: null,
    totalVehiclesServed: 5,
  },
  {
    id: 'SLOT-B02',
    zone: 'Zone B',
    type: 'STANDARD',
    distance: 52,
    state: 'FREE',
    currentVehicleId: null,
    reservedForVehicleId: null,
    occupiedSince: null,
    expectedReleaseTime: null,
    reservationExpiresAt: null,
    totalVehiclesServed: 2,
  },
  {
    id: 'SLOT-B03',
    zone: 'Zone B',
    type: 'RESERVED',
    distance: 58,
    state: 'RESERVED',
    currentVehicleId: null,
    reservedForVehicleId: 'RES-CORP-01',
    occupiedSince: null,
    expectedReleaseTime: null,
    reservationExpiresAt: 20, // Booked for t=10, grace expires at t=20
    totalVehiclesServed: 1,
  },
  {
    id: 'SLOT-B04',
    zone: 'Zone B',
    type: 'ACCESSIBLE',
    distance: 62,
    state: 'OCCUPIED',
    currentVehicleId: 'PROC-103',
    reservedForVehicleId: null,
    occupiedSince: 0,
    expectedReleaseTime: 50,
    reservationExpiresAt: null,
    totalVehiclesServed: 3,
  },
  {
    id: 'SLOT-B05',
    zone: 'Zone B',
    type: 'EV_CHARGER',
    distance: 68,
    state: 'FREE',
    currentVehicleId: null,
    reservedForVehicleId: null,
    occupiedSince: null,
    expectedReleaseTime: null,
    reservationExpiresAt: null,
    totalVehiclesServed: 2,
  },
  {
    id: 'SLOT-B06',
    zone: 'Zone B',
    type: 'STANDARD',
    distance: 75,
    state: 'FREE',
    currentVehicleId: null,
    reservedForVehicleId: null,
    occupiedSince: null,
    expectedReleaseTime: null,
    reservationExpiresAt: null,
    totalVehiclesServed: 4,
  },

  // Zone C - Extended Facility (85m - 110m)
  {
    id: 'SLOT-C01',
    zone: 'Zone C',
    type: 'STANDARD',
    distance: 88,
    state: 'FREE',
    currentVehicleId: null,
    reservedForVehicleId: null,
    occupiedSince: null,
    expectedReleaseTime: null,
    reservationExpiresAt: null,
    totalVehiclesServed: 1,
  },
  {
    id: 'SLOT-C02',
    zone: 'Zone C',
    type: 'STANDARD',
    distance: 94,
    state: 'FREE',
    currentVehicleId: null,
    reservedForVehicleId: null,
    occupiedSince: null,
    expectedReleaseTime: null,
    reservationExpiresAt: null,
    totalVehiclesServed: 2,
  },
  {
    id: 'SLOT-C03',
    zone: 'Zone C',
    type: 'MAINTENANCE',
    distance: 102,
    state: 'MAINTENANCE',
    currentVehicleId: null,
    reservedForVehicleId: null,
    occupiedSince: null,
    expectedReleaseTime: null,
    reservationExpiresAt: null,
    totalVehiclesServed: 0,
  },
];

export const INITIAL_VEHICLES: VehiclePCB[] = [
  // Currently Parked Processes
  {
    id: 'PROC-101',
    licensePlate: 'MH-12-RS-1001',
    category: 'NORMAL',
    isEV: false,
    needsAccessible: false,
    arrivalTime: 0,
    expectedDuration: 25,
    hasReservation: false,
    reservationStartTime: null,
    reservationGraceExpiresAt: null,
    agingCycles: 0,
    state: 'PARKED',
    allocatedSlotId: 'SLOT-A01',
    actualParkStartTime: 0,
    expectedExitTime: 25,
    actualExitTime: null,
    fineIncurred: 0,
  },
  {
    id: 'EV-IONIQ-5',
    licensePlate: 'DL-01-EV-5500',
    category: 'NORMAL',
    isEV: true,
    needsAccessible: false,
    arrivalTime: 5,
    expectedDuration: 35,
    hasReservation: false,
    reservationStartTime: null,
    reservationGraceExpiresAt: null,
    agingCycles: 0,
    state: 'PARKED',
    allocatedSlotId: 'SLOT-A02',
    actualParkStartTime: 5,
    expectedExitTime: 40,
    actualExitTime: null,
    fineIncurred: 0,
  },
  {
    id: 'PROC-102',
    licensePlate: 'KA-03-MB-4040',
    category: 'NORMAL',
    isEV: false,
    needsAccessible: false,
    arrivalTime: 2,
    expectedDuration: 16,
    hasReservation: false,
    reservationStartTime: null,
    reservationGraceExpiresAt: null,
    agingCycles: 0,
    state: 'PARKED',
    allocatedSlotId: 'SLOT-B01',
    actualParkStartTime: 2,
    expectedExitTime: 18,
    actualExitTime: null,
    fineIncurred: 0,
  },
  {
    id: 'PROC-103',
    licensePlate: 'TN-07-AC-7890',
    category: 'DISABLED',
    isEV: false,
    needsAccessible: true,
    arrivalTime: 0,
    expectedDuration: 50,
    hasReservation: false,
    reservationStartTime: null,
    reservationGraceExpiresAt: null,
    agingCycles: 0,
    state: 'PARKED',
    allocatedSlotId: 'SLOT-B04',
    actualParkStartTime: 0,
    expectedExitTime: 50,
    actualExitTime: null,
    fineIncurred: 0,
  },

  // Reserved Process
  {
    id: 'RES-CORP-01',
    licensePlate: 'DL-04-VIP-0001',
    category: 'VIP',
    isEV: false,
    needsAccessible: false,
    arrivalTime: 10,
    expectedDuration: 45,
    hasReservation: true,
    reservationStartTime: 10,
    reservationGraceExpiresAt: 20,
    agingCycles: 0,
    state: 'READY',
    allocatedSlotId: null,
    actualParkStartTime: null,
    expectedExitTime: null,
    actualExitTime: null,
    fineIncurred: 0,
  },

  // Ready Queue Waiting Vehicles
  {
    id: 'PROC-NORM-99',
    licensePlate: 'HR-26-AB-3344',
    category: 'NORMAL',
    isEV: false,
    needsAccessible: false,
    arrivalTime: 2,
    expectedDuration: 45,
    hasReservation: false,
    reservationStartTime: null,
    reservationGraceExpiresAt: null,
    agingCycles: 20, // Skipped twice, accumulating aging!
    state: 'READY',
    allocatedSlotId: null,
    actualParkStartTime: null,
    expectedExitTime: null,
    actualExitTime: null,
    fineIncurred: 0,
  },
  {
    id: 'EV-NEXON-02',
    licensePlate: 'MH-14-EV-8822',
    category: 'NORMAL',
    isEV: true,
    needsAccessible: false,
    arrivalTime: 6,
    expectedDuration: 30,
    hasReservation: false,
    reservationStartTime: null,
    reservationGraceExpiresAt: null,
    agingCycles: 10,
    state: 'READY',
    allocatedSlotId: null,
    actualParkStartTime: null,
    expectedExitTime: null,
    actualExitTime: null,
    fineIncurred: 0,
  },
  {
    id: 'POLICE-INTERCEPT',
    licensePlate: 'DL-01-POL-100',
    category: 'POLICE',
    isEV: false,
    needsAccessible: false,
    arrivalTime: 9,
    expectedDuration: 20,
    hasReservation: false,
    reservationStartTime: null,
    reservationGraceExpiresAt: null,
    agingCycles: 0,
    state: 'READY',
    allocatedSlotId: null,
    actualParkStartTime: null,
    expectedExitTime: null,
    actualExitTime: null,
    fineIncurred: 0,
  },
  {
    id: 'ACCESSIBLE-VAN-01',
    licensePlate: 'UP-16-DIS-4412',
    category: 'DISABLED',
    isEV: false,
    needsAccessible: true,
    arrivalTime: 8,
    expectedDuration: 60,
    hasReservation: false,
    reservationStartTime: null,
    reservationGraceExpiresAt: null,
    agingCycles: 0,
    state: 'READY',
    allocatedSlotId: null,
    actualParkStartTime: null,
    expectedExitTime: null,
    actualExitTime: null,
    fineIncurred: 0,
  },
];

export const INITIAL_LOGS: AuditLogEntry[] = [
  {
    id: 'log-boot-01',
    timestamp: 0,
    cycle: 0,
    vehicleId: null,
    slotId: null,
    eventType: 'CONFIG_CHANGE',
    severity: 'info',
    message: '[OS BOOT] Smart Parking Resource Scheduler initialized with Demand Threshold=50%, Grace=10m.',
  },
  {
    id: 'log-boot-02',
    timestamp: 0,
    cycle: 0,
    vehicleId: 'PROC-101',
    slotId: 'SLOT-A01',
    eventType: 'ALLOCATION',
    severity: 'success',
    message: '[ALLOCATION] Bound process PROC-101 to resource SLOT-A01.',
  },
  {
    id: 'log-boot-03',
    timestamp: 5,
    cycle: 1,
    vehicleId: 'EV-IONIQ-5',
    slotId: 'SLOT-A02',
    eventType: 'ALLOCATION',
    severity: 'success',
    message: '[ALLOCATION] Dedicated EV process EV-IONIQ-5 allocated to SLOT-A02.',
  },
  {
    id: 'log-boot-04',
    timestamp: 10,
    cycle: 2,
    vehicleId: 'POLICE-INTERCEPT',
    slotId: null,
    eventType: 'ENQUEUE',
    severity: 'info',
    message: '[ENQUEUE] High-Urgency process POLICE-INTERCEPT entered Ready Queue.',
  },
];
